import Head from "next/head";
import Home from "./home";
import axios from "axios";

export default function Index({categories}) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
            </Head>
            <Home categories={categories}/>
        </div>
    );
}

export const getServerSideProps = async (ctx) => {
    const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`);

    return {
        props: {
            categories: res ? res.data : [],
        },
    };
};
