import Head from "next/head";
import Home from "./home";
import axios from "axios";

export default function Index({categoryList,productList}) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
            </Head>
            <Home categoryList={categoryList} productList={productList}/>
        </div>
    );
}

export const getServerSideProps = async (ctx) => {
    const categoryRes = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`);
    const productRes = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/products`);
    

    return {
        props: {
            categoryList: categoryRes ? categoryRes.data : [],
            productList: productRes ? productRes.data : [],
        },
    };
};
